FROM rust:1-slim-trixie AS builder
WORKDIR /usr/src/myapp
COPY . .
RUN apt-get update && apt-get install -y nasm
RUN cargo install --profile release --path .

FROM alpine:latest AS packer
COPY --from=builder /usr/local/cargo/bin/byteshaver /usr/local/bin/byteshaver
RUN apk add --no-cache upx && \
    upx --best --ultra-brute /usr/local/bin/byteshaver

FROM debian:trixie-slim
RUN apt-get update && apt-get install -y libc6 && rm -rf /var/lib/apt/lists/*
COPY --from=packer /usr/local/bin/byteshaver /usr/local/bin/byteshaver
WORKDIR /targets
CMD ["byteshaver"]
