#!/usr/bin/env bash
# Regenerates docs/dependency-licenses.md: the license inventory of every
# crate distributed in the release binaries (union of the linux-musl and
# windows-gnullvm targets). Requires cargo + python3.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/dependency-licenses.md"

python3 - "$OUT" <<'PYEOF'
import json, subprocess, sys, os, datetime

targets = [("x86_64-unknown-linux-musl", "linux-musl static-pie (CLI, GUI)"),
           ("x86_64-pc-windows-gnullvm", "windows-gnullvm/ucrt (CLI, GUI)")]
union = {}   # (name, version) -> {"licenses": set, "targets": set}
for tgt, label in targets:
    # plain cargo metadata: parses manifests + resolves the graph only —
    # no build scripts run, so no pkg-config/CC/toolchain setup is needed
    out = subprocess.run(["cargo", "metadata", "--format-version", "1",
                          "--filter-platform", tgt],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"cargo metadata failed for {tgt}: {out.stderr[:400]}")
    d = json.loads(out.stdout)
    pkgs = {p["id"]: p for p in d["packages"]}
    root = next(p for p in d["packages"] if p["name"] == "byteshaver")
    node = next(n for n in d["resolve"]["nodes"] if n["id"] == root["id"])
    seen, stack = set(), [root["id"]]
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        p = pkgs[pid]
        key = (p["name"], p["version"])
        union.setdefault(key, {"lic": p.get("license") or "UNLICENSED", "targets": set()})["targets"].add(label)
        node = next(n for n in d["resolve"]["nodes"] if n["id"] == pid)
        stack.extend(node["dependencies"])

lines = [
    "# Dependency license inventory",
    "",
    "Every crate distributed inside the release binaries (union of the shipped",
    "targets), regenerated by `tools/license-inventory.sh` — run that script",
    "after changing dependencies. All listed licenses are permissive",
    "(MIT / Apache-2.0 / BSD / Zlib / CC0 / Unicode families); the copyleft",
    "components and their compliance notes live in",
    "[THIRD-PARTY-NOTICES.md](../THIRD-PARTY-NOTICES.md).",
    "",
    f"Generated: {datetime.date.today().isoformat()} · crates: {len(union)}",
    "",
    "| crate | version | license(s) | shipped in |",
    "|---|---|---|---|",
]
for (name, ver), v in sorted(union.items()):
    t = "both" if len(v["targets"]) == 2 else ("linux" if "linux" in list(v["targets"])[0] else "windows")
    lines.append(f"| {name} | {ver} | {v['lic']} | {t} |")
lines.append("")

open(sys.argv[1], "w").write("\n".join(lines))
print(f"wrote {sys.argv[1]} ({len(union)} crates)")
PYEOF
